fix db-setup

diff --git a/backend-flask/bin/db-setup b/backend-flask/bin/db-setup
--- a/backend-flask/bin/db-setup
+++ b/backend-flask/bin/db-setup
@@ -1,4 +1,6 @@
-#! /usr/bin/bash -e # stop if it fails at any point
+#! /usr/bin/bash
+
+#set -e # stop if it fails at any point
 
 CYAN='\033[1;36m'
 NO_COLOR='\033[0m'
